--------------------------------------------------------
--  DDL for Table GD_ADM_FACT_RENG_TMP
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_ADM_FACT_RENG_TMP" ("CODSEDE" VARCHAR2(6 BYTE), "CODCOMPANIA" VARCHAR2(6 BYTE), "NUMERO_FACTURA" VARCHAR2(20 BYTE), "NUMERO_LINEA" NUMBER(3,0), "CODIGO_ITEM" VARCHAR2(20 BYTE), "NUMERO_CUOTA" NUMBER(2,0), "MONTO_RENGLON" NUMBER(12,2), "DESCRIPCION" VARCHAR2(120 BYTE), "C005" VARCHAR2(20 BYTE), "FILAID" UROWID (4000), "BAREMO" NUMBER(10,2), "N001" NUMBER(2,0)) ;
