--------------------------------------------------------
--  Constraints for Table GD_ADM_CUOTAS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_ADM_CUOTAS" MODIFY ("PERSONAID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_CUOTAS" MODIFY ("NUMHISTORIA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_CUOTAS" MODIFY ("NUMPRESUPUESTO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_CUOTAS" MODIFY ("NUMCUOTA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_CUOTAS" MODIFY ("CODSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_CUOTAS" MODIFY ("MTOCUOTA" NOT NULL ENABLE);
