--------------------------------------------------------
--  DDL for Table GD_ADM_FACTURAS
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_ADM_FACTURAS" ("CODSEDE" VARCHAR2(6 BYTE), "CODCOMPANIA" VARCHAR2(6 BYTE), "NUMERO_FACTURA" VARCHAR2(20 BYTE), "FECHA_FACTURA" DATE, "NUMHISTORIA" VARCHAR2(20 BYTE), "NUMERO_CONTROL" VARCHAR2(20 BYTE), "CAJA_NUMERO" VARCHAR2(10 BYTE), "CODSERVICIO" VARCHAR2(20 BYTE), "CODESPECIALISTA" VARCHAR2(20 BYTE), "RESPONSABLE_PAGO_NOMBRE" VARCHAR2(60 BYTE), "RESPONSABLE_PAGO_LETRAID" VARCHAR2(1 BYTE), "RESPONSABLE_PAGO_CI" VARCHAR2(20 BYTE), "CODESPECIALIDAD" VARCHAR2(3 BYTE)) ;

   COMMENT ON COLUMN "GDCNO"."GD_ADM_FACTURAS"."CODESPECIALIDAD" IS 'Código de la Especialidad del servicIo que se Factura';
