--------------------------------------------------------
--  Constraints for Table GD_ADM_FACT_TMP
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_ADM_FACT_TMP" MODIFY ("CODSEDE" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACT_TMP" MODIFY ("CODCOMPANIA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACT_TMP" MODIFY ("NUMERO_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACT_TMP" MODIFY ("FECHA_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACT_TMP" MODIFY ("NUMHISTORIA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACT_TMP" MODIFY ("NUMERO_CONTROL" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACT_TMP" ADD CONSTRAINT "GD_ADM_FACT_TMP_PK" PRIMARY KEY ("CODSEDE", "CODCOMPANIA", "NUMERO_FACTURA") USING INDEX  ENABLE;
