--------------------------------------------------------
--  Constraints for Table GD_ADM_COBROS_RENG
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_ADM_COBROS_RENG" MODIFY ("CODSEDE" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_COBROS_RENG" MODIFY ("CODCOMPANIA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_COBROS_RENG" MODIFY ("NUMERO_COBRO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_COBROS_RENG" MODIFY ("NUMERO_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_COBROS_RENG" MODIFY ("NUMERO_LINEA" NOT NULL ENABLE);
