--------------------------------------------------------
--  DDL for Table GD_ADM_FACTURAS_RENG
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_ADM_FACTURAS_RENG" ("CODSEDE" VARCHAR2(6 BYTE), "CODCOMPANIA" VARCHAR2(6 BYTE), "NUMERO_FACTURA" VARCHAR2(20 BYTE), "NUMERO_LINEA" NUMBER(3,0), "CODIGO_ITEM" VARCHAR2(20 BYTE), "NUMERO_CUOTA" NUMBER(2,0), "MONTO_RENGLON" NUMBER(12,2), "DESCRIPCION" VARCHAR2(120 BYTE), "UNIDAD" VARCHAR2(20 BYTE), "BAREMO" NUMBER(10,2) DEFAULT 0) ;
