--------------------------------------------------------
--  DDL for Table GD_ADM_CUOTAS
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_ADM_CUOTAS" ("CODSEDE" VARCHAR2(6 BYTE), "CODCOMPANIA" VARCHAR2(6 BYTE), "PERSONAID" NUMBER(10,0), "NUMHISTORIA" VARCHAR2(10 BYTE), "NUMPRESUPUESTO" VARCHAR2(11 BYTE), "NUMCUOTA" NUMBER(3,0), "CODSERVICIO" VARCHAR2(6 BYTE), "FECCUOTA" DATE, "MTOCUOTA" NUMBER(12,2), "FECPAGO" DATE, "STSCUOTA" VARCHAR2(3 BYTE), "NUMFACTURA" VARCHAR2(12 BYTE), "NUMRENGLON" NUMBER(2,0), "CODIGO_ITEM" VARCHAR2(20 BYTE), "BAREMO" NUMBER(10,2)) ;
