--------------------------------------------------------
--  DDL for Table GD_ADM_COBROS_RENG
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_ADM_COBROS_RENG" ("CODSEDE" VARCHAR2(6 BYTE), "CODCOMPANIA" VARCHAR2(6 BYTE), "NUMERO_COBRO" VARCHAR2(20 BYTE), "NUMERO_FACTURA" VARCHAR2(20 BYTE), "NUMERO_LINEA" NUMBER(3,0), "TIPO_INSTRUMENTO" VARCHAR2(20 BYTE), "NUMERO_INSTRUMENTO" VARCHAR2(20 BYTE), "BANCO_INSTRUMENTO" VARCHAR2(20 BYTE), "MONTO_INSTRUMENTO" NUMBER(12,2), "FECHA_COBRO" DATE) ;
