--------------------------------------------------------
--  Constraints for Table GD_ADM_FACT_RENG_TMP
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_ADM_FACT_RENG_TMP" MODIFY ("CODSEDE" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACT_RENG_TMP" MODIFY ("CODCOMPANIA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACT_RENG_TMP" MODIFY ("NUMERO_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACT_RENG_TMP" MODIFY ("NUMERO_LINEA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACT_RENG_TMP" MODIFY ("CODIGO_ITEM" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACT_RENG_TMP" ADD CONSTRAINT "GD_ADM_FACT_RENG_TMP_PK" PRIMARY KEY ("CODSEDE", "CODCOMPANIA", "NUMERO_FACTURA", "NUMERO_LINEA") USING INDEX  ENABLE;
