--------------------------------------------------------
--  Constraints for Table GD_ADM_FACTURAS_RENG
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_ADM_FACTURAS_RENG" MODIFY ("CODSEDE" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACTURAS_RENG" MODIFY ("CODCOMPANIA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACTURAS_RENG" MODIFY ("NUMERO_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACTURAS_RENG" MODIFY ("NUMERO_LINEA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACTURAS_RENG" MODIFY ("CODIGO_ITEM" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACTURAS_RENG" ADD CONSTRAINT "GD_ADM_FACTURAS_RENG_PK" PRIMARY KEY ("CODCOMPANIA", "NUMERO_FACTURA", "NUMERO_LINEA") USING INDEX  ENABLE;
