--------------------------------------------------------
--  Constraints for Table GD_ADM_FACTURAS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_ADM_FACTURAS" MODIFY ("CODSEDE" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACTURAS" MODIFY ("CODCOMPANIA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACTURAS" MODIFY ("NUMERO_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACTURAS" MODIFY ("FECHA_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACTURAS" MODIFY ("NUMHISTORIA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACTURAS" MODIFY ("NUMERO_CONTROL" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_ADM_FACTURAS" ADD CONSTRAINT "GD_ADM_FACTURAS_PK" PRIMARY KEY ("CODCOMPANIA", "NUMERO_FACTURA") USING INDEX  ENABLE;
