--------------------------------------------------------
--  Constraints for Table GD_CC_RESULTADO_ENCUESTA
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_CC_RESULTADO_ENCUESTA" MODIFY ("ENCREALIZADAID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_RESULTADO_ENCUESTA" MODIFY ("NUMLINEA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_RESULTADO_ENCUESTA" ADD CONSTRAINT "PK_GD_CC_RESULTADO_ENCUESTA" PRIMARY KEY ("ENCREALIZADAID", "NUMLINEA") USING INDEX  ENABLE;
