--------------------------------------------------------
--  DDL for Table GD_CC_CITAS
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_CC_CITAS" ("CITAID" VARCHAR2(10 BYTE), "CODSEDE" VARCHAR2(6 BYTE), "CODSERVICIO" VARCHAR2(6 BYTE), "CODESPECIALIDAD" VARCHAR2(3 BYTE), "CODESPECIALISTA" VARCHAR2(6 BYTE), "PERSONAID" NUMBER(10,0), "NUMPRESUPUESTO" VARCHAR2(11 BYTE), "HORAINICIO" DATE, "DURACION" NUMBER(2,0), "NUMCITA" VARCHAR2(10 BYTE), "STSCITA" VARCHAR2(1 BYTE) DEFAULT 'T') ;
