--------------------------------------------------------
--  Constraints for Table GD_CC_TEXTO_LOTE
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_CC_TEXTO_LOTE" MODIFY ("LOTETEXTOID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_TEXTO_LOTE" MODIFY ("NUMTEXTO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_TEXTO_LOTE" MODIFY ("LISTAID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_TEXTO_LOTE" ADD CONSTRAINT "PK_GD_CC_TEXTOLOTE" PRIMARY KEY ("LOTETEXTOID", "NUMTEXTO") USING INDEX  ENABLE;
