--------------------------------------------------------
--  Constraints for Table GD_CC_ESPEC_OPER
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_CC_ESPEC_OPER" MODIFY ("LOGINUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_ESPEC_OPER" MODIFY ("CATEGORIALLAMADA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_ESPEC_OPER" MODIFY ("PRIORIDAD" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_ESPEC_OPER" ADD CONSTRAINT "PK_GD_CC_ESPEC_OPER" PRIMARY KEY ("LOGINUSUARIO", "CATEGORIALLAMADA") USING INDEX  ENABLE;
