--------------------------------------------------------
--  Constraints for Table GD_CC_CITAS_HORARIO_ESPEC
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_CC_CITAS_HORARIO_ESPEC" MODIFY ("CODESPECIALISTA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS_HORARIO_ESPEC" MODIFY ("CODSEDE" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS_HORARIO_ESPEC" MODIFY ("CODSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS_HORARIO_ESPEC" MODIFY ("DIASEMANA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS_HORARIO_ESPEC" MODIFY ("HORADIA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS_HORARIO_ESPEC" ADD CONSTRAINT "GD_CC_CITAS_HORARIO_ESPEC_PK" PRIMARY KEY ("CODSEDE", "CODSERVICIO", "CODESPECIALISTA", "DIASEMANA", "HORADIA") USING INDEX  ENABLE;
