--------------------------------------------------------
--  Constraints for Table GD_CC_RENG_ENCUESTAS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_CC_RENG_ENCUESTAS" MODIFY ("ENCUESTAID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_RENG_ENCUESTAS" MODIFY ("NUMLINEA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_RENG_ENCUESTAS" MODIFY ("TEXTOLINEA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_RENG_ENCUESTAS" MODIFY ("TIPOOPCIONES" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_RENG_ENCUESTAS" MODIFY ("NUMPUNTOS" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_RENG_ENCUESTAS" ADD CONSTRAINT "GD_CC_RENG_ENCUESTAS_PK" PRIMARY KEY ("ENCUESTAID", "NUMLINEA") USING INDEX  ENABLE;
