--------------------------------------------------------
--  Constraints for Table GD_CC_LLAMADAS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_CC_LLAMADAS" MODIFY ("LLAMADAID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_LLAMADAS" MODIFY ("PERSONAID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_LLAMADAS" MODIFY ("LISTAID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_LLAMADAS" MODIFY ("STSLLAMADA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_LLAMADAS" ADD CONSTRAINT "PK_GD_CC_LLAMADAS" PRIMARY KEY ("LLAMADAID") USING INDEX  ENABLE;
