--------------------------------------------------------
--  Constraints for Table GD_CC_CITAS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_CC_CITAS" MODIFY ("CITAID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS" MODIFY ("CODSEDE" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS" MODIFY ("CODSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS" MODIFY ("PERSONAID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS" MODIFY ("HORAINICIO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS" MODIFY ("DURACION" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS" ADD CONSTRAINT "GD_CC_CITAS_PK" PRIMARY KEY ("CITAID") USING INDEX  ENABLE;
  ALTER TABLE "GDCNO"."GD_CC_CITAS" ADD CONSTRAINT "GD_CC_CITAS_UK1" UNIQUE ("PERSONAID", "HORAINICIO") USING INDEX  ENABLE;
