--------------------------------------------------------
--  DDL for Table GD_CJA_CAJAS
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_CJA_CAJAS" ("CODSEDE" VARCHAR2(6 BYTE), "CAJA_NUMERO" VARCHAR2(10 BYTE), "CODIGO_USUARIO" VARCHAR2(25 CHAR), "FECHA_APERTURA" DATE, "FECHA_CIERRE" DATE, "FACTURA_SERIE" VARCHAR2(20 BYTE), "CONTROL_SERIE" VARCHAR2(20 BYTE), "FACTURA_INICIAL" VARCHAR2(20 BYTE) DEFAULT 0, "FECHA_FACTURA_I" DATE, "FACTURA_FINAL" VARCHAR2(20 BYTE) DEFAULT 0, "FECHA_FACTURA_F" DATE) ;
