--------------------------------------------------------
--  Constraints for Table GD_CC_OPERADORES_SESION
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_CC_OPERADORES_SESION" MODIFY ("SESIONLLAMADAID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_OPERADORES_SESION" MODIFY ("LOGINUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_OPERADORES_SESION" MODIFY ("ESTACIONID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_OPERADORES_SESION" MODIFY ("FECENTRADA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_OPERADORES_SESION" ADD CONSTRAINT "PK_GD_CC_OPERADORES_SESION" PRIMARY KEY ("SESIONLLAMADAID", "LOGINUSUARIO") USING INDEX  ENABLE;
