--------------------------------------------------------
--  DDL for Table GD_CC_OPERADORES_SESION
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_CC_OPERADORES_SESION" ("SESIONLLAMADAID" VARCHAR2(10 CHAR), "LOGINUSUARIO" VARCHAR2(16 CHAR), "ESTACIONID" NUMBER(3,0), "FECENTRADA" DATE, "STSOPERADORSESION" VARCHAR2(3 BYTE), "FECSALIDA" DATE, "CANTLLAMADASASIG" NUMBER(3,0)) ;
