--------------------------------------------------------
--  Constraints for Table GD_CC_ENCUESTAS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_CC_ENCUESTAS" MODIFY ("ENCUESTAID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_ENCUESTAS" MODIFY ("NOMENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_ENCUESTAS" MODIFY ("TIPOENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_ENCUESTAS" MODIFY ("CATEGORIALLAMADA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_ENCUESTAS" ADD CONSTRAINT "GD_CC_ENCUESTAS_PK" PRIMARY KEY ("ENCUESTAID") USING INDEX  ENABLE;
