--------------------------------------------------------
--  DDL for Table GD_CC_LLAMADAS
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_CC_LLAMADAS" ("LLAMADAID" VARCHAR2(10 BYTE), "PERSONAID" NUMBER(10,0), "CODSERVICIO" VARCHAR2(6 BYTE), "LISTAID" NUMBER(10,0), "STSLLAMADA" VARCHAR2(3 BYTE), "SESIONLLAMADAIDASIG" NUMBER(10,0), "LOGINUSUARIO" VARCHAR2(16 BYTE), "FECREGLLAMADA" DATE, "SESIONLLAMADAIDREAL" NUMBER(10,0), "OPERADORIDREAL" VARCHAR2(16 BYTE), "FECREALLLAMADA" DATE, "EVALRESULTADOLLAMADA" VARCHAR2(3 BYTE), "TEXTORESULTADOLLAMADA" VARCHAR2(120 BYTE), "FECCOMPCLIENTE" DATE, "CODSEDE" VARCHAR2(6 BYTE), "CODESPECIALIDAD" VARCHAR2(3 BYTE), "CODESPECIALISTA" VARCHAR2(6 BYTE)) ;
