--------------------------------------------------------
--  Constraints for Table GD_CC_CITAS_CONTADOR
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_CC_CITAS_CONTADOR" MODIFY ("CODSEDE" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS_CONTADOR" MODIFY ("CODSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS_CONTADOR" MODIFY ("HORAINICIO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS_CONTADOR" MODIFY ("CODESPECIALISTA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_CC_CITAS_CONTADOR" ADD CONSTRAINT "GD_CC_CITAS_CONTADOR_PK" PRIMARY KEY ("CODSEDE", "CODSERVICIO", "HORAINICIO", "CODESPECIALISTA") USING INDEX  ENABLE;
