--------------------------------------------------------
--  Constraints for Table GD_GEN_PARAMETROS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_GEN_PARAMETROS" MODIFY ("CODSEDE" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_PARAMETROS" MODIFY ("CODPARAMETRO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_PARAMETROS" MODIFY ("VALORPARAMETRO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_PARAMETROS" ADD CONSTRAINT "GD_GEN_PARAMETROS_PK" PRIMARY KEY ("CODSEDE", "CODPARAMETRO", "VALORPARAMETRO") USING INDEX  ENABLE;
