REM INSERTING into GDCNO.GD_GEN_SEDES
SET DEFINE OFF;
Insert into GDCNO.GD_GEN_SEDES (CODSEDE,NOMSEDE,NUMHISTORIA,LETRAHISTORIA) values ('8','CNO Capitolio','2810','C');
Insert into GDCNO.GD_GEN_SEDES (CODSEDE,NOMSEDE,NUMHISTORIA,LETRAHISTORIA) values ('2','ORTODONCIA CHACAITO','54225',null);
Insert into GDCNO.GD_GEN_SEDES (CODSEDE,NOMSEDE,NUMHISTORIA,LETRAHISTORIA) values ('3','CNO BRION','34261','A');
Insert into GDCNO.GD_GEN_SEDES (CODSEDE,NOMSEDE,NUMHISTORIA,LETRAHISTORIA) values ('1','CNO Las Mercedes','30971','B');
