--------------------------------------------------------
--  Constraints for Table GD_GEN_CONTADORES_DOCUMENTOS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_GEN_CONTADORES_DOCUMENTOS" MODIFY ("CODCOMPANIA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_CONTADORES_DOCUMENTOS" MODIFY ("TIPO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_CONTADORES_DOCUMENTOS" MODIFY ("SUB_TIPO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_CONTADORES_DOCUMENTOS" MODIFY ("ANO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_CONTADORES_DOCUMENTOS" MODIFY ("CONTADOR" NOT NULL ENABLE);
