--------------------------------------------------------
--  Constraints for Table GD_GEN_ESPECIALIDADES
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_GEN_ESPECIALIDADES" MODIFY ("CODSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_ESPECIALIDADES" MODIFY ("CODESPECIALIDAD" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_ESPECIALIDADES" MODIFY ("NOMBESPECIALIDAD" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_ESPECIALIDADES" ADD CONSTRAINT "PK_GD_GEN_ESPECIALIDADES" PRIMARY KEY ("CODSERVICIO", "CODESPECIALIDAD") USING INDEX  ENABLE;
