--------------------------------------------------------
--  DDL for Table GD_GEN_PERSONAS
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_GEN_PERSONAS" ("PERSONAID" NUMBER(10,0), "NOMBPERSONA" VARCHAR2(120 BYTE), "APELLIDOSPERSONA" VARCHAR2(120 BYTE), "EMAILPERSONA" VARCHAR2(160 BYTE), "NUMHISTORIA" VARCHAR2(10 BYTE), "FECNACIMIENTO" DATE, "GENERO" VARCHAR2(1 BYTE), "CODSEDE" VARCHAR2(6 BYTE), "TELHABITACION" VARCHAR2(20 BYTE), "TELCELULAR" VARCHAR2(20 BYTE), "TELTRABAJO" VARCHAR2(20 BYTE), "TELOTROS" VARCHAR2(60 BYTE), "MSGRECEPCION" VARCHAR2(1024 BYTE), "MSGFACTURACION" VARCHAR2(1024 BYTE), "LETRACEDULA" VARCHAR2(1 BYTE) DEFAULT 'V', "NUMCEDULA" NUMBER(12,0), "PERSONACONTACTO" VARCHAR2(120 BYTE), "NACIONALIDAD" VARCHAR2(60 BYTE), "PAISORIGEN" VARCHAR2(30 BYTE), "TELCONTACTO" VARCHAR2(20 BYTE), "ESTADOCIVIL" VARCHAR2(1 BYTE) DEFAULT 'S', "DIRHABITACION" VARCHAR2(500 BYTE), "REGIONHABITACION" VARCHAR2(60 BYTE), "ENTIDADHABITACION" VARCHAR2(60 BYTE), "MUNICIPIOHABITACION" VARCHAR2(60 BYTE), "OBSERVACIONES" VARCHAR2(1500 BYTE), "NOTAS" VARCHAR2(1500 BYTE), "FECINGRESO" DATE) ;

   COMMENT ON COLUMN "GDCNO"."GD_GEN_PERSONAS"."LETRACEDULA" IS 'Letra de la cédula del paciente';
   COMMENT ON COLUMN "GDCNO"."GD_GEN_PERSONAS"."NUMCEDULA" IS 'Número de la Cédula del Paciente';
   COMMENT ON COLUMN "GDCNO"."GD_GEN_PERSONAS"."PERSONACONTACTO" IS 'Nombre completo de la persona contacto del Paciente';
   COMMENT ON COLUMN "GDCNO"."GD_GEN_PERSONAS"."NACIONALIDAD" IS 'Nacionalidad del paciente';
   COMMENT ON COLUMN "GDCNO"."GD_GEN_PERSONAS"."PAISORIGEN" IS 'Pais de Origen del Paciente';
   COMMENT ON COLUMN "GDCNO"."GD_GEN_PERSONAS"."TELCONTACTO" IS 'Teléfono de contacto del Paciente';
   COMMENT ON COLUMN "GDCNO"."GD_GEN_PERSONAS"."ESTADOCIVIL" IS 'Estado Civil del Paciente';
   COMMENT ON COLUMN "GDCNO"."GD_GEN_PERSONAS"."DIRHABITACION" IS 'Dirección de habitación';
   COMMENT ON COLUMN "GDCNO"."GD_GEN_PERSONAS"."REGIONHABITACION" IS 'Región donde se ubica la Habitración del Paciente';
   COMMENT ON COLUMN "GDCNO"."GD_GEN_PERSONAS"."ENTIDADHABITACION" IS 'Entidad donde se encuentra la Habotaciön del Paciente';
   COMMENT ON COLUMN "GDCNO"."GD_GEN_PERSONAS"."MUNICIPIOHABITACION" IS 'Municipio donde se encuentra la Habitación';
