--------------------------------------------------------
--  Constraints for Table GD_GEN_SERVICIOS_CLINICOS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_GEN_SERVICIOS_CLINICOS" MODIFY ("CODSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_SERVICIOS_CLINICOS" MODIFY ("NOMSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_SERVICIOS_CLINICOS" ADD CONSTRAINT "GD_GEN_SERVICIOS_CLINICOS_PK" PRIMARY KEY ("CODSERVICIO") USING INDEX  ENABLE;
