--------------------------------------------------------
--  DDL for Table GD_GEN_HISTORIAS_PERSONA
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_GEN_HISTORIAS_PERSONA" ("PERSONAID" NUMBER(10,0), "CODSEDE" VARCHAR2(6 BYTE), "CODSERVICIO" VARCHAR2(6 BYTE), "NUMHISTORIA" VARCHAR2(10 BYTE), "NUMHISTORIAANTERIOR" VARCHAR2(10 BYTE), "FECULTVISITA" DATE, "FECPROXCITA" DATE, "CODESPECIALIDAD" VARCHAR2(3 BYTE), "CODESPECIALISTA" VARCHAR2(6 BYTE)) ;
