--------------------------------------------------------
--  Constraints for Table GD_GEN_DIAS_FERIADOS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_GEN_DIAS_FERIADOS" MODIFY ("DIAFERIADOID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_DIAS_FERIADOS" MODIFY ("FECFERIADO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_DIAS_FERIADOS" ADD CONSTRAINT "GD_GEN_DIAS_FERIADOS_PK" PRIMARY KEY ("DIAFERIADOID") USING INDEX  ENABLE;
