--------------------------------------------------------
--  DDL for Table GD_GEN_ESPECIALISTAS
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_GEN_ESPECIALISTAS" ("CODESPECIALISTA" VARCHAR2(6 BYTE), "CODSEDE" VARCHAR2(6 BYTE), "CODSERVICIO" VARCHAR2(6 BYTE), "NOMESPECIALISTA" VARCHAR2(64 BYTE), "APELLESPECIALISTA" VARCHAR2(64 BYTE), "LOGINUSUARIO" VARCHAR2(20 BYTE), "STSESPECIALISTA" VARCHAR2(3 BYTE), "CODESPECIALIDAD" VARCHAR2(3 BYTE), "NUMCEDULA" VARCHAR2(12 BYTE), "LETRACEDULA" VARCHAR2(1 BYTE), "NUMIDESPECIALISTA" VARCHAR2(20 BYTE), "LETRAIDESPECIALISTA" VARCHAR2(1 BYTE), "INDGRUPO" VARCHAR2(1 BYTE) DEFAULT 'N', "DESCGRUPO" VARCHAR2(500 BYTE)) ;

   COMMENT ON COLUMN "GDCNO"."GD_GEN_ESPECIALISTAS"."INDGRUPO" IS 'Indica si se refiere es a un grupo';
   COMMENT ON COLUMN "GDCNO"."GD_GEN_ESPECIALISTAS"."DESCGRUPO" IS 'Descripcion del Grupo. Puede ser nombres y rif de los participantes del grupo';
