--------------------------------------------------------
--  DDL for Table GD_GEN_USUARIOS
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_GEN_USUARIOS" ("CODSEDE" VARCHAR2(6 BYTE), "LOGINUSUARIO" VARCHAR2(20 BYTE), "NOMUSUARIO" VARCHAR2(80 BYTE), "STSUSUARIO" VARCHAR2(3 BYTE) DEFAULT 'ACT', "TIPOUSUARIO" VARCHAR2(3 BYTE), "CODCOMPANIA" VARCHAR2(6 BYTE), "INICIALES" VARCHAR2(6 BYTE)) 

--   COMMENT ON COLUMN "GDCNO"."GD_GEN_USUARIOS"."TIPOUSUARIO" IS 'Puede valer ''OCC'' y ''SCC'' para CC'
