--------------------------------------------------------
--  Constraints for Table GD_GEN_PERSONAS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_GEN_PERSONAS" MODIFY ("PERSONAID" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_PERSONAS" ADD CONSTRAINT "PK_GD_GEN_PERSONAS" PRIMARY KEY ("PERSONAID") USING INDEX  ENABLE;
  ALTER TABLE "GDCNO"."GD_GEN_PERSONAS" ADD CONSTRAINT "UQ_GD_GEN_PERSONA_NUMHISTORIA" UNIQUE ("NUMHISTORIA") USING INDEX  ENABLE;
