--------------------------------------------------------
--  Constraints for Table GD_GEN_ESPECIALISTAS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_GEN_ESPECIALISTAS" MODIFY ("CODESPECIALISTA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_ESPECIALISTAS" MODIFY ("CODSEDE" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_ESPECIALISTAS" MODIFY ("CODSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_ESPECIALISTAS" MODIFY ("NOMESPECIALISTA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_ESPECIALISTAS" MODIFY ("APELLESPECIALISTA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_ESPECIALISTAS" MODIFY ("STSESPECIALISTA" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_GEN_ESPECIALISTAS" ADD CONSTRAINT "GD_GEN_ESPECIALISTAS_PK" PRIMARY KEY ("CODSEDE", "CODSERVICIO", "CODESPECIALIDAD", "CODESPECIALISTA") USING INDEX  ENABLE;
