--------------------------------------------------------
--  Constraints for Table GD_HM_OD_HISTORIAS_ORTO
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_HM_OD_HISTORIAS_ORTO" ADD CONSTRAINT "GD_HM_OD_HISTORIASORTO_PK" PRIMARY KEY ("TRATAMIENTOID") USING INDEX  ENABLE
  ALTER TABLE "GDCNO"."GD_HM_OD_HISTORIAS_ORTO" MODIFY ("TRATAMIENTOID" NOT NULL ENABLE)
  ALTER TABLE "GDCNO"."GD_HM_OD_HISTORIAS_ORTO" MODIFY ("FECHA" NOT NULL ENABLE)
  ALTER TABLE "GDCNO"."GD_HM_OD_HISTORIAS_ORTO" MODIFY ("NUMHISTORIA" NOT NULL ENABLE)
  ALTER TABLE "GDCNO"."GD_HM_OD_HISTORIAS_ORTO" MODIFY ("CODESPECIALISTA" NOT NULL ENABLE)
