--------------------------------------------------------
--  Constraints for Table GD_HM_ODONTOLOGIA
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_HM_ODONTOLOGIA" ADD CONSTRAINT "GD_HM_ODONTOLOGIA_PK" PRIMARY KEY ("TRATAMIENTOID") USING INDEX  ENABLE
  ALTER TABLE "GDCNO"."GD_HM_ODONTOLOGIA" MODIFY ("TRATAMIENTOID" NOT NULL ENABLE)
  ALTER TABLE "GDCNO"."GD_HM_ODONTOLOGIA" MODIFY ("FECHA" NOT NULL ENABLE)
