--------------------------------------------------------
--  Constraints for Table GD_HM_OD_HISTORIAS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_HM_OD_HISTORIAS" ADD CONSTRAINT "GD_HM_OD_HISTORIAS_PK" PRIMARY KEY ("TRATAMIENTOID") USING INDEX  ENABLE
  ALTER TABLE "GDCNO"."GD_HM_OD_HISTORIAS" MODIFY ("TRATAMIENTOID" NOT NULL ENABLE)
  ALTER TABLE "GDCNO"."GD_HM_OD_HISTORIAS" MODIFY ("FECHA" NOT NULL ENABLE)
  ALTER TABLE "GDCNO"."GD_HM_OD_HISTORIAS" MODIFY ("DIENTE" NOT NULL ENABLE)
  ALTER TABLE "GDCNO"."GD_HM_OD_HISTORIAS" MODIFY ("NUMHISTORIA" NOT NULL ENABLE)
