--------------------------------------------------------
--  DDL for Table GD_HM_RAYOSX
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_HM_RAYOSX" ("NUMHISTORIA" VARCHAR2(10 BYTE), "CODESPECIALISTA" VARCHAR2(16 BYTE), "FECHA" DATE, "OBSERVACIONES" VARCHAR2(4000 BYTE), "CODSERVICIO" VARCHAR2(6 BYTE), "CODSEDE" VARCHAR2(6 BYTE), "TRATAMIENTOID" VARCHAR2(20 BYTE), "NUMTRATAMIENTO" VARCHAR2(20 BYTE), "IMGIMG" BLOB, "IMGMIME" VARCHAR2(32 BYTE), "IMGFILE" VARCHAR2(128 BYTE), "ESPECIALIDAD" NUMBER(2,0))
