--------------------------------------------------------
--  DDL for Table GD_HM_OD_HALLAZGOS
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_HM_OD_HALLAZGOS" ("HALLAZGO" NUMBER(4,0), "DESCRIPCION" VARCHAR2(60 BYTE), "MOVILIDAD_DENTARIA" VARCHAR2(1 BYTE) DEFAULT '0', "RESTAURACION_DEFECTUOSA" VARCHAR2(1 BYTE) DEFAULT '0', "STATUS" VARCHAR2(1 BYTE) DEFAULT '1', "AGRUPA_CARAS" VARCHAR2(1 BYTE) DEFAULT '0', "DIENTE_AUSENTE" VARCHAR2(1 BYTE) DEFAULT '0') ;
