--------------------------------------------------------
--  Constraints for Table GD_INV_ITEMS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_INV_ITEMS" MODIFY ("CODSEDE" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_INV_ITEMS" MODIFY ("CODIGO_ITEM" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_INV_ITEMS" MODIFY ("DESCRIPCION_ITEM" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_INV_ITEMS" MODIFY ("PVP_1" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_INV_ITEMS" ADD CONSTRAINT "GD_INV_ITM_PK" PRIMARY KEY ("CODIGO_ITEM", "CODSEDE") USING INDEX  ENABLE;
