--------------------------------------------------------
--  DDL for Table GD_PPTO_PRESUPUESTOS
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_PPTO_PRESUPUESTOS" ("CODSEDE" VARCHAR2(6 BYTE), "NUMPRESUPUESTO" VARCHAR2(20 BYTE), "FECPRESUPUESTO" DATE, "NUMHISTORIA" VARCHAR2(10 BYTE), "STSPRESUPUESTO" VARCHAR2(3 BYTE), "CODTABULADOR" VARCHAR2(2 BYTE), "CODESPECIALISTA" VARCHAR2(6 BYTE), "CODSERVICIO" VARCHAR2(6 BYTE), "CODESPECIALIDAD" VARCHAR2(3 BYTE), "LETRAIDRESPPAGO" VARCHAR2(1 BYTE), "NUMIDRESPPAGO" VARCHAR2(20 BYTE), "NOMBRESPPAGO" VARCHAR2(80 BYTE), "PERSONAID" NUMBER(10,0)) ;
