--------------------------------------------------------
--  Constraints for Table GD_PPTO_PRESUPUESTOS
--------------------------------------------------------

  ALTER TABLE "GDCNO"."GD_PPTO_PRESUPUESTOS" MODIFY ("CODSEDE" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_PPTO_PRESUPUESTOS" MODIFY ("NUMPRESUPUESTO" NOT NULL ENABLE);
  ALTER TABLE "GDCNO"."GD_PPTO_PRESUPUESTOS" ADD CONSTRAINT "GD_PPTO_PRESUPUESTOS_PK" PRIMARY KEY ("NUMPRESUPUESTO") USING INDEX  ENABLE;
