--------------------------------------------------------
--  DDL for Table GD_PPTO_RENG_PRESUPUESTO
--------------------------------------------------------

  CREATE TABLE "GDCNO"."GD_PPTO_RENG_PRESUPUESTO" ("CODSEDE" VARCHAR2(6 BYTE), "NUMPRESUPUESTO" VARCHAR2(20 BYTE), "NUMRENGLON" NUMBER(2,0), "CODIGO_ITEM" VARCHAR2(20 BYTE), "PRECIOUNITARIO" NUMBER(16,2), "INICIAL" NUMBER(5,0), "AJUSTE" NUMBER(6,2), "CANTRENGLON" NUMBER(2,0), "FACTOR" VARCHAR2(1 BYTE), "NUMCUOTAS" NUMBER(3,0), "MTOCUOTA" NUMBER(16,2), "BAREMOUNITARIO" NUMBER(10,2), "BAREMOCUOTA" NUMBER(10,2)) ;
