--------------------------------------------------------
-- Archivo creado  - sábado-julio-11-2015   
--------------------------------------------------------
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\DEMO_CUST_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\DEMO_ORDER_ITEMS_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\DEMO_ORD_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\DEMO_PROD_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\DEPT_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\EMP_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ENCUESTAS_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_LISTAS_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_SCRIPTS_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_TEXTOS_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CJA_FACTTMP_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_COMPANIAS_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_LISTAS_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\SQ_PERSONAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\XLIB_SEQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_OPERADORES_ESTACIONES.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\V_DETALLE_DIA.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\ACT_STS_CUOTA_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\VALIDA_LINEA_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\XLIB_LOGS_BI_TRG.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\ENVIARMENSAJESMS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\ES_NUMERICO.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\SQUIRREL_GET_ERROR_OFFSET.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_CAJAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_CC_AGENDAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_CC_ENCUESTAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_CC_LISTAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_GEN_COMPANIAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_GEN_GENERAL.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_GEN_USUARIOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_HM_ODIAGRAMA.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_PRESUPUESTO.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_UTIL.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_WEBSERVICEDANA.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\QUEST_REFLECTOR.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\SAMPLE_DATA_PKG.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\SAMPLE_PKG.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\SOAP_API.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\XLIB_COMPONENT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\XLIB_HTTP.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\XLIB_JASPERREPORTS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\XLIB_LOG.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_CAJAS_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_CC_AGENDAS_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_CC_ENCUESTAS_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_CC_LISTAS_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_GEN_COMPANIAS_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_GEN_GENERAL_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_GEN_USUARIOS_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_HM_ODIAGRAMA_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_PRESUPUESTO_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_UTIL_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PROC_WEBSERVICEDANA_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\SAMPLE_DATA_PKG_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\SAMPLE_PKG_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\SOAP_API_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\XLIB_COMPONENT_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\XLIB_HTTP_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\XLIB_JASPERREPORTS_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\XLIB_LOG_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\XLOG.sql
