--------------------------------------------------------
-- Archivo creado  - domingo-julio-12-2015   
--------------------------------------------------------
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_DIENTES.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_LIGADURAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_ORTO.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_DIENTES_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_LIGADURAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_ORTO_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_INDEX1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_DNTS_IDX1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_DNTS_IDX2.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_LIG_IDX1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIASORTO_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIASORTO_INDEX1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_DIENTES_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_LIGADURAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_OD_HISTORIAS_ORTO_CONSTRAINT.sql
