--------------------------------------------------------
-- Archivo creado  - jueves-julio-09-2015   
--------------------------------------------------------
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_COBROS_RENG.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_CUOTAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACT_RENG_TMP.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACT_TMP.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACTURAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACTURAS_RENG.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_CONTADOR.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_DISPONIBILIDAD.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_HORARIO_ESPEC.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_MOV.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CJA_CAJAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_DIAS_FERIADOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_HISTORIAS_PERSONA.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_PERSONAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_INV_COLETILLA_ITEM.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_INV_ITEMS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_PPTO_PRESUPUESTOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_PPTO_RENG_PRESUPUESTO.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_COBROS_RENG_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_CUOTAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACT_RENG_TMP_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACT_TMP_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACTURAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACTURAS_RENG_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_CONTADOR_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_DISPONIBILIDAD_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_HORARIO_ESPEC_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_MOV_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CJA_CAJAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_DIAS_FERIADOS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_HISTORIAS_PERSONA_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_PERSONAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_INV_COLETILLA_ITEM_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_INV_ITEMS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_PPTO_PRESUPUESTOS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_PPTO_RENG_PRESUPUESTO_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_COBRENG_I1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_CUOTAS_INDEX1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_CUOTA_I1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACT_RENG_TMP_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACT_TMP_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACTURAS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACTURAS_RENG_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_INDEX2.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_INDEX1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_UK1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_CONTADOR_PK1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_I1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_DISPONIBILIDAD_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_HORARIO_ESPEC_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_MOV_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_MOV_INDEX1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CJA_CJS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CJA_CAJAS_INDEX1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_DIAS_FERIADOS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_HISTORIAS_PERS_IDX1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_PERSONAS_SEDE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_PERSONAS_I2.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PK_GD_GEN_PERSONAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\UQ_GD_GEN_PERSONA_NUMHISTORIA.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_PERSONAS_NUMCEDULA.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_INV_ITM_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_INV_ITM_I1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_PPTO_PRESUPUESTOS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_PPTO_PRESUP_I1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_PPTO_PRESUP_I2.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_PPTO_RENG_PPTO_INDEX1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_COBROS_RENG_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_CUOTAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACT_RENG_TMP_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACT_TMP_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACTURAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_FACTURAS_RENG_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_CONTADOR_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_DISPONIBILIDAD_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_HORARIO_ESPEC_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CJA_CAJAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_DIAS_FERIADOS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_HISTORIAS_PERSONA_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_PERSONAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_INV_COLETILLA_ITEM_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_INV_ITEMS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_PPTO_PRESUPUESTOS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_PPTO_RENG_PRESUPUESTO_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_CITAS_REFCONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_HISTORIAS_PERSONA_REFCONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\ACT_STS_CUOTA.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\VALIDA_LINEA.sql
