--------------------------------------------------------
-- Archivo creado  - jueves-julio-09-2015   
--------------------------------------------------------
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_PARAMETROS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_APINAMIENTO.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_ESPECIALIDADES.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SEDES.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_PERFILES.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ESPEC_OPER.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ARCOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_EXTRACCIONES.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_ESPECIALISTAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ANGULOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_CONTADORES_DOCUMENTOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_AUX.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_RENG_ENCUESTAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_CLASIFICACIONESQ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_APSP.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ENCUESTA_REALIZADA.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_RESULTADO_ENCUESTA.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_OPCIONES_MENU.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_CLASIFICACION.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SERVICIOS_CLINICOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_SESIONES_LLAMADAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_COMPANIAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_BANDAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_EXPRMM.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_MORDIDAPRF.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ESTACIONES_LLAMADAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_TUBOS1VEZ.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_MORDIDAANT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_MORDIDAPOST.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ESPEDENTULOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ENCUESTAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ELASTICOSM.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_LLAMADAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_BANCOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ELASTICOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_DIENTES.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_DISTANCIAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_REFERENCIAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_SCRIPTS_LLAMADAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_DIASTEMAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SERV_SEDES.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_OPERADORES_SESION.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_TUBOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SEGURIDAD_APP.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_TEXTO_LOTE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_TEXTOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_DEF_LISTAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_LOTE_TEXTOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_PARAMETROS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_APINAMIENTO_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_ESPECIALIDADES_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SEDES_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_PERFILES_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ESPEC_OPER_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ARCOS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_EXTRACCIONES_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_ESPECIALISTAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ANGULOS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_CONTADORES_DOCUMENTOS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_AUX_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_RENG_ENCUESTAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_CLASIFICACIONESQ_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_APSP_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ENCUESTA_REALIZADA_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_RESULTADO_ENCUESTA_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_OPCIONES_MENU_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_CLASIFICACION_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SERVICIOS_CLINICOS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_SESIONES_LLAMADAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_COMPANIAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_BANDAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_EXPRMM_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_MORDIDAPRF_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ESTACIONES_LLAMADAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_TUBOS1VEZ_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_MORDIDAANT_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_MORDIDAPOST_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ESPEDENTULOS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ENCUESTAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ELASTICOSM_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_LLAMADAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_BANCOS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ELASTICOS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_DIENTES_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_DISTANCIAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_REFERENCIAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_SCRIPTS_LLAMADAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_DIASTEMAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SERV_SEDES_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_OPERADORES_SESION_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_TUBOS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SEGURIDAD_APP_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_TEXTO_LOTE_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_TEXTOS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_DEF_LISTAS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_LOTE_TEXTOS_DATA_TABLE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_PARAMETROS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_APINAMIENTO_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PK_GD_GEN_ESPECIALIDADES.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SEDES_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_PERFILES_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PK_GD_CC_ESPEC_OPER.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ARCOS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_EXTRACCIONES_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_ESPECIALISTAS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ANGULOS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\HM_ORTO_AUX_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_RENG_ENCUESTAS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_CLASIFICACIONES_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_APSP_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PK_GD_CC_ENCUESTA_REALIZADA.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PK_GD_CC_RESULTADO_ENCUESTA.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_OPCIONES_MENU_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_OPCMENU_I1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_OPCMENU_I2.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_CLASUFICACION_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SERVICIOS_CLINICOS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PK_GD_CC_SESIONES_LLAMADAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_COMPANIAS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_BANDAS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_EXPRMM_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_MORDIDAPRF_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PK_GD_CC_ESTACIONES_LLAMADAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_TUBOS1VEZ_1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_MORDIDA_ORTO_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_MORDIDAPOST_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ESPEDENTULOS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ENCUESTAS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ELASTICOSM_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PK_GD_CC_LLAMADAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_BANCOS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ELASTICOS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_DIENTES_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_DISTANCIAS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_SCRIPTS_LLAMADAS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_DIASTEMAS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SERV_SEDES_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PK_GD_CC_OPERADORES_SESION.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_TUBOS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SEGURIDAD_APP_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SEGURIDAD_APP_INDEX1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PK_GD_CC_TEXTOLOTE.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_TEXTOS_PK.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_TEXTOS_UK1.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PK_GD_CC_LISTAS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\PK_GD_CC_ENVIO_TEXTOS.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_PARAMETROS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_APINAMIENTO_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_ESPECIALIDADES_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SEDES_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_PERFILES_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ESPEC_OPER_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ARCOS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_EXTRACCIONES_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_ESPECIALISTAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ANGULOS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_CONTADORES_DOCUMENTOS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_AUX_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_RENG_ENCUESTAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_CLASIFICACIONESQ_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_APSP_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ENCUESTA_REALIZADA_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_RESULTADO_ENCUESTA_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_OPCIONES_MENU_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_CLASIFICACION_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SERVICIOS_CLINICOS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_SESIONES_LLAMADAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_COMPANIAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_BANDAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_EXPRMM_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_MORDIDAPRF_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ESTACIONES_LLAMADAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_TUBOS1VEZ_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_MORDIDAANT_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_MORDIDAPOST_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ESPEDENTULOS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_ENCUESTAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ELASTICOSM_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_LLAMADAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_ADM_BANCOS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_ELASTICOS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_DIENTES_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_DISTANCIAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_REFERENCIAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_SCRIPTS_LLAMADAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_DIASTEMAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SERV_SEDES_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_OPERADORES_SESION_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_HM_ORTO_TUBOS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SEGURIDAD_APP_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_TEXTO_LOTE_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_TEXTOS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_DEF_LISTAS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_CC_LOTE_TEXTOS_CONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_ESPECIALISTAS_REFCONSTRAINT.sql
@C:\Users\LuisCapriles\Documents\_ProyectosLC\CNO\BackUps\LOCAL\GD_GEN_SERV_SEDES_REFCONSTRAINT.sql
