--------------------------------------------------------
--  DDL for Package Body PROC_CC_ENCUESTAS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "GDCNO"."PROC_CC_ENCUESTAS" AS
    PROCEDURE REGISTRA_ENCUESTA (pENCREALIZADAID NUMBER,  pNUMLINEA NUMBER,  pRESULTADO VARCHAR2) IS
    BEGIN
        INSERT INTO GD_CC_RESULTADO_ENCUESTA (ENCREALIZADAID, NUMLINEA, RESULTADO)
        VALUES (pENCREALIZADAID,  pNUMLINEA,  pRESULTADO);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            UPDATE GD_CC_RESULTADO_ENCUESTA
            SET  RESULTADO = pRESULTADO
            where ENCREALIZADAID = pENCREALIZADAID 
            and NUMLINEA = pNUMLINEA;
    END;
END PROC_CC_ENCUESTAS;
